language: go
go_import_path: github.com/whiteblock/genesis
sudo: false
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      go: 1.12.x
      install:
        - go get -u github.com/golang/lint/golint
      script:
        - go test ./...
        - golint ./...
