global:
  scrape_interval:     30s
  scrape_timeout:      10s
  evaluation_interval: 1m

  # Attach labels to time series or alerts when communicating with
  # external systems like alert manager or remote storage.
  external_labels:
      monitor: 'prometheus-monitor'

# Load and evaluate rules in file every evaluation_interval.
rule_files:
  # - "some.rules" # add if wanted

scrape_configs:

  - job_name: 'prometheus-server'
    static_configs:
      - targets: [ '0.0.0.0:9090' ]

  - job_name: 'rchain-node'
    scrape_interval: 1m

    metrics_path: "/metrics"
    static_configs:
      - targets: ['127.0.0.1:40403']
      #- targets: [ 'host.docker.internal:40403' ]
# https://github.com/prometheus/prometheus/blob/master/docs/configuration/configuration.md#remote_write
remote_write:
- url: "https://influxdb-rchain.whiteblock.io/api/v1/prom/write?db=stats&u=root&p=3j2qEneHSRBhbUjR5Td5GDe1kNRRHzYOb3U"
  tls_config:
    insecure_skip_verify: true
#remote_read:
#  - url: "http://localhost:8086/api/v1/prom/read?db=prometheus"
